name: metrics
on:
 # Schedule daily updates 00:00 UTC
  schedule:
  - cron: '0 5 * * *'
  push: 
    branches: ["master"]
      
jobs:
  job-isocalendar-half:
    runs-on: ubuntu-latest
    name: Half-year commit calendar
    steps:
    - uses: NikPACodes/metrics@master
      with:
        filename: metrics.plugin.isocalendar.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_isocalendar: yes

  job-isocalendar-year:
    runs-on: ubuntu-latest
    name: Year commit calendar
    steps:
    - uses: NikPACodes/metrics@master
      with:
        filename: metrics.plugin.isocalendar.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_isocalendar: yes
        plugin_isocalendar_duration: full-year
